name: HealthCheck
on:
  push:
    branches:
      - master
  # schedule:
  #   - cron:  '* * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokeapi.co/api/v2/pokemon/?limit=50
          max-attempts: 3 
          retry-delay: 5s 