name: Hello World!
# on is "trigger" action for workflow, in this case this is "push" action
on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    name: Hello World
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: show date
        run: |
          current_date=$(TZ="Europe/Helsinki" date +'%a %b %e %T %Z %Y')
          echo "Current Date (in Finland's time zone): $current_date"
      - name: Run ls -l
        run: |
          current_content=$(ls -l)
          echo $current_content

  